###!!!                     Autogenerated file                       !!!
###!!!Any changes made to this file may be overwritten automatically!!!

reset
set xlabel "Frame Number"
set ylabel "Dispatch Time (ms)"
set format x "%.f frame"
set format y "%.3f ms"
set grid ytics mytics  # draw lines for each ytics and mytics
set mytics 0.1         # set the spacing for the mytics
set grid
set key horizontal noinvert left
set title "Dispatch Times for shader: RGBA" font ", 16"
plot \
"../../Data/Cube_0#0.data" using 1 w lines lc 0 t "Cube_0",\
"../../Data/Cube_1#0.data" using 1 w lines lc 1 t "Cube_1",\
"../../Data/Cube_2#0.data" using 1 w lines lc 2 t "Cube_2",\
"../../Data/Cube_3#0.data" using 1 w lines lc 3 t "Cube_3",\
"../../Data/Cube_4#0.data" using 1 w lines lc 4 t "Cube_4",\
"../../Data/Cube_5#0.data" using 1 w lines lc 5 t "Cube_5",\
"../../Data/Cube_6#0.data" using 1 w lines lc 6 t "Cube_6",\
"../../Data/Cube_7#0.data" using 1 w lines lc 7 t "Cube_7",\
"../../Data/Cube_8#0.data" using 1 w lines lc 8 t "Cube_8",\
