###!!!                     Autogenerated file                       !!!
###!!!Any changes made to this file may be overwritten automatically!!!

reset
set xlabel "Complexity level"
set ylabel "Dispatch Time (ms)"
set boxwidth 0.05
set style data histogram
set style histogram cluster
set style boxplot nooutliers
set xtics ("lvl 0" 0.000000,"lvl 1" 0.100000,"lvl 2" 0.200000,"lvl 3" 0.300000,"lvl 4" 0.400000,"lvl 5" 0.500000,"lvl 6" 0.600000,"lvl 7" 0.700000,"lvl 8" 0.800000)
set xrange [-0.1:0.900000]
set yrange [0:]
set title "Dispatch Times for shader: RGBA" font ", 16"
plot \
"../../Data/Cube_0#0.data" using (0.000000):1:xticlabels(1) w boxplot t "Cube lvl 0",\
"../../Data/Cube_1#0.data" using (0.100000):1:xticlabels(1) w boxplot t "Cube lvl 1",\
"../../Data/Cube_2#0.data" using (0.200000):1:xticlabels(1) w boxplot t "Cube lvl 2",\
"../../Data/Cube_3#0.data" using (0.300000):1:xticlabels(1) w boxplot t "Cube lvl 3",\
"../../Data/Cube_4#0.data" using (0.400000):1:xticlabels(1) w boxplot t "Cube lvl 4",\
"../../Data/Cube_5#0.data" using (0.500000):1:xticlabels(1) w boxplot t "Cube lvl 5",\
"../../Data/Cube_6#0.data" using (0.600000):1:xticlabels(1) w boxplot t "Cube lvl 6",\
"../../Data/Cube_7#0.data" using (0.700000):1:xticlabels(1) w boxplot t "Cube lvl 7",\
"../../Data/Cube_8#0.data" using (0.800000):1:xticlabels(1) w boxplot t "Cube lvl 8",\
