function(print_variables)
    message(STATUS "---------------------------------------")
    message(STATUS "CMAKE_SOURCE_DIR is ${CMAKE_SOURCE_DIR}")
    message(STATUS "CMAKE_BINARY_DIR is ${CMAKE_BINARY_DIR}")
    message(STATUS "PROJECT_NAME is ${PROJECT_NAME}")
    message(STATUS "PROJECT_SOURCE_DIR is ${PROJECT_SOURCE_DIR}")
    message(STATUS "PROJECT_BINARY_DIR is ${PROJECT_BINARY_DIR}")
    message(STATUS "PROJECT_VERSION is ${PROJECT_VERSION}")
    message(STATUS "CMAKE_CURRENT_SOURCE_DIR is ${CMAKE_CURRENT_SOURCE_DIR}")
    message(STATUS "CMAKE_CURRENT_BINARY_DIR is ${CMAKE_CURRENT_BINARY_DIR}")
    message(STATUS "CMAKE_CURRENT_LIST_FILE is ${CMAKE_CURRENT_LIST_FILE}")
    message(STATUS "CMAKE_CURRENT_LIST_DIR is ${CMAKE_CURRENT_LIST_DIR}")
    message(STATUS "CMAKE_BUILD_TYPE is ${CMAKE_BUILD_TYPE}")
    message(STATUS "---------------------------------------")
endfunction(print_variables)