###!!!                     Autogenerated file                       !!!
###!!!Any changes made to this file may be overwritten automatically!!!

reset
file="../../Data/data.MergedData"
set title "" font ", 16"
set xlabel "Frame Number"
set ylabel "Frame Draw Time (ms)"
set format x "%.f frame"
set format y "%.3f ms"
set grid ytics mytics  # draw lines for each ytics and mytics
set mytics 0.1         # set the spacing for the mytics
set grid
set key horizontal noinvert left
plot \
file using 15        w lines lc 14t "shader-14",\
file using 31        w lines lc 14t "shader-14",\
file using 47        w lines lc 14t "shader-14",\
file using 63        w lines lc 14t "shader-14",\
