###!!!                     Autogenerated file                       !!!
###!!!Any changes made to this file may be overwritten automatically!!!

reset
set xlabel "Frame Number"
set ylabel "Dispatch Time (ms)"
set format x "%.f frame"
set format y "%.3f ms"
set grid ytics mytics  # draw lines for each ytics and mytics
set mytics 0.1         # set the spacing for the mytics
set grid
set key horizontal noinvert left
set title "Dispatch Times for shader: R" font ", 16"
plot \
"../../Data/Forest_A#0.data" using 1 w lines lc 0 t "Forest_A",\
"../../Data/Forest_BC4#0.data" using 1 w lines lc 1 t "Forest_BC4",\
"../../Data/Scene0_A#0.data" using 1 w lines lc 2 t "Scene0_A",\
"../../Data/Scene0_BC4#0.data" using 1 w lines lc 3 t "Scene0_BC4",\
