###!!!                     Autogenerated file                       !!!
###!!!Any changes made to this file may be overwritten automatically!!!

reset
set xlabel "Scene Name"
set ylabel "Dispatch Time (ms)"
set boxwidth 0.05
set style data histogram
set style histogram cluster
set style boxplot nooutliers
set xtics ("Forest A" 0.000000,"Forest BC4" 0.100000,"Scene0 A" 0.200000,"Scene0 BC4" 0.300000)
set xrange [-0.1:0.800000]
set yrange [0:]
set title "Dispatch Times for shader: R" font ", 16"
plot \
"../../Data/Forest_A#1.data" using (0.000000):1:xticlabels(1) w boxplot t "Forest A",\
"../../Data/Forest_BC4#1.data" using (0.100000):1:xticlabels(1) w boxplot t "Forest BC4",\
"../../Data/Scene0_A#1.data" using (0.200000):1:xticlabels(1) w boxplot t "Scene0 A",\
"../../Data/Scene0_BC4#1.data" using (0.300000):1:xticlabels(1) w boxplot t "Scene0 BC4",\
