###!!!                     Autogenerated file                       !!!
###!!!Any changes made to this file may be overwritten automatically!!!

reset
set xlabel "Test Case"
set ylabel "Frame Draw Time (ms)"
set boxwidth 0.05
set style data histogram
set style histogram cluster
set style boxplot nooutliers
set xtics (" Minimal-SIMPLE" 0.000000," DICE-SIMPLE" 0.100000," RayGen-SIMPLE" 0.200000," Close1-SIMPLE" 0.300000," Close2-SIMPLE" 0.400000," Minimal-NS" 0.500000," DICE-NS" 0.600000," RayGen-NS" 0.700000," Close1-NS" 0.800000," Close2-NS" 0.900000," Minimal" 1.000000," DICE" 1.100000," RayGen" 1.200000," Close1" 1.300000," Close2" 1.400000," RayGen-Debug" 1.500000)
set xrange [-0.1:1.600000]
set yrange [:4]
set title "Scene 3" font ", 16"
plot \
"../../Data/Scene5#0.data" using (0.000000):1:xticlabels(1) w boxplot t "Minimal-SIMPLE",\
"../../Data/Scene5#1.data" using (0.100000):1:xticlabels(1) w boxplot t "DICE-SIMPLE",\
"../../Data/Scene5#2.data" using (0.200000):1:xticlabels(1) w boxplot t "RayGen-SIMPLE",\
"../../Data/Scene5#3.data" using (0.300000):1:xticlabels(1) w boxplot t "Close1-SIMPLE",\
"../../Data/Scene5#4.data" using (0.400000):1:xticlabels(1) w boxplot t "Close2-SIMPLE",\
"../../Data/Scene5#5.data" using (0.500000):1:xticlabels(1) w boxplot t "Minimal-NS",\
"../../Data/Scene5#6.data" using (0.600000):1:xticlabels(1) w boxplot t "DICE-NS",\
"../../Data/Scene5#7.data" using (0.700000):1:xticlabels(1) w boxplot t "RayGen-NS",\
"../../Data/Scene5#8.data" using (0.800000):1:xticlabels(1) w boxplot t "Close1-NS",\
"../../Data/Scene5#9.data" using (0.900000):1:xticlabels(1) w boxplot t "Close2-NS",\
"../../Data/Scene5#10.data" using (1.000000):1:xticlabels(1) w boxplot t "Minimal",\
"../../Data/Scene5#11.data" using (1.100000):1:xticlabels(1) w boxplot t "DICE",\
"../../Data/Scene5#12.data" using (1.200000):1:xticlabels(1) w boxplot t "RayGen",\
"../../Data/Scene5#13.data" using (1.300000):1:xticlabels(1) w boxplot t "Close1",\
"../../Data/Scene5#14.data" using (1.400000):1:xticlabels(1) w boxplot t "Close2",\
"../../Data/Scene5#15.data" using (1.500000):1:xticlabels(1) w boxplot t "RayGen-Debug",\
