###!!!                     Autogenerated file                       !!!
###!!!Any changes made to this file may be overwritten automatically!!!

reset
set title "" font ", 16"
set xlabel "Frame Number"
set ylabel "Frame Draw Time (ms)"
set format x "%.f frame"
set format y "%.3f ms"
set grid ytics mytics  # draw lines for each ytics and mytics
set mytics 0.1         # set the spacing for the mytics
set grid
set key horizontal noinvert left
set yrange [0:10]
set yrange [0:10]
plot \
"../../Data/Scene2#0.data" using 1 w lines lc 0t "shader-RayGen-SIMPLE",\
"../../Data/Scene2#1.data" using 1 w lines lc 1t "shader-RayGen-SIMPLE",\
"../../Data/Scene2#2.data" using 1 w lines lc 2t "shader-RayGen-SIMPLE",\
"../../Data/Scene2#3.data" using 1 w lines lc 3t "shader-RayGen-SIMPLE",\
"../../Data/Scene2#4.data" using 1 w lines lc 4t "shader-RayGen-SIMPLE",\
"../../Data/Scene2#5.data" using 1 w lines lc 5t "shader-RayGen-SIMPLE",\
"../../Data/Scene2#6.data" using 1 w lines lc 6t "shader-RayGen-SIMPLE",\
"../../Data/Scene2#7.data" using 1 w lines lc 7t "shader-RayGen-SIMPLE",\
"../../Data/Scene2#8.data" using 1 w lines lc 8t "shader-RayGen-SIMPLE",\
"../../Data/Scene2#9.data" using 1 w lines lc 9t "shader-RayGen-SIMPLE",\
"../../Data/Scene2#10.data" using 1 w lines lc 10t "shader-RayGen-SIMPLE",\
"../../Data/Scene2#11.data" using 1 w lines lc 11t "shader-RayGen-SIMPLE",\
"../../Data/Scene2#12.data" using 1 w lines lc 12t "shader-RayGen-SIMPLE",\
"../../Data/Scene2#13.data" using 1 w lines lc 13t "shader-RayGen-SIMPLE",\
"../../Data/Scene2#14.data" using 1 w lines lc 14t "shader-RayGen-SIMPLE",\
"../../Data/Scene2#15.data" using 1 w lines lc 15t "shader-RayGen-SIMPLE",\
