###!!!                     Autogenerated file                       !!!
###!!!Any changes made to this file may be overwritten automatically!!!

reset
set title "" font ", 16"
set xlabel "Frame Number"
set ylabel "Frame Draw Time (ms)"
set format x "%.f frame"
set format y "%.3f ms"
set grid ytics mytics  # draw lines for each ytics and mytics
set mytics 0.1         # set the spacing for the mytics
set grid
set key horizontal noinvert left
set yrange [0:10]
set yrange [0:10]
plot \
"../../Data/Scene3#0.data" using 1 w lines lc 0t "shader-Close1-SIMPLE",\
"../../Data/Scene3#1.data" using 1 w lines lc 1t "shader-Close1-SIMPLE",\
"../../Data/Scene3#2.data" using 1 w lines lc 2t "shader-Close1-SIMPLE",\
"../../Data/Scene3#3.data" using 1 w lines lc 3t "shader-Close1-SIMPLE",\
"../../Data/Scene3#4.data" using 1 w lines lc 4t "shader-Close1-SIMPLE",\
"../../Data/Scene3#5.data" using 1 w lines lc 5t "shader-Close1-SIMPLE",\
"../../Data/Scene3#6.data" using 1 w lines lc 6t "shader-Close1-SIMPLE",\
"../../Data/Scene3#7.data" using 1 w lines lc 7t "shader-Close1-SIMPLE",\
"../../Data/Scene3#8.data" using 1 w lines lc 8t "shader-Close1-SIMPLE",\
"../../Data/Scene3#9.data" using 1 w lines lc 9t "shader-Close1-SIMPLE",\
"../../Data/Scene3#10.data" using 1 w lines lc 10t "shader-Close1-SIMPLE",\
"../../Data/Scene3#11.data" using 1 w lines lc 11t "shader-Close1-SIMPLE",\
"../../Data/Scene3#12.data" using 1 w lines lc 12t "shader-Close1-SIMPLE",\
"../../Data/Scene3#13.data" using 1 w lines lc 13t "shader-Close1-SIMPLE",\
"../../Data/Scene3#14.data" using 1 w lines lc 14t "shader-Close1-SIMPLE",\
"../../Data/Scene3#15.data" using 1 w lines lc 15t "shader-Close1-SIMPLE",\
