###!!!                     Autogenerated file                       !!!
###!!!Any changes made to this file may be overwritten automatically!!!

reset
set xlabel "Frame Number"
set ylabel "Dispatch Time (ms)"
set format x "%.f frame"
set format y "%.3f ms"
set grid ytics mytics  # draw lines for each ytics and mytics
set mytics 0.1         # set the spacing for the mytics
set grid
set key horizontal noinvert left
set title "Geometry complexity levels - Scene Forest" font ", 16"
plot \
"../../Data/Forest_0#0.data" using 1 w lines lc 0 t "Forest lvl 0",\
"../../Data/Forest_1#0.data" using 1 w lines lc 1 t "Forest lvl 1",\
"../../Data/Forest_2#0.data" using 1 w lines lc 2 t "Forest lvl 2",\
"../../Data/Forest_3#0.data" using 1 w lines lc 3 t "Forest lvl 3",\
"../../Data/Forest_4#0.data" using 1 w lines lc 4 t "Forest lvl 4",\
"../../Data/Forest_5#0.data" using 1 w lines lc 5 t "Forest lvl 5",\
"../../Data/Forest_6#0.data" using 1 w lines lc 6 t "Forest lvl 6",\
"../../Data/Forest_7#0.data" using 1 w lines lc 7 t "Forest lvl 7",\
"../../Data/Forest_8#0.data" using 1 w lines lc 8 t "Forest lvl 8",\
