###!!!                     Autogenerated file                       !!!
###!!!Any changes made to this file may be overwritten automatically!!!

reset
set xlabel "Complexity level"
set ylabel "Dispatch Time (ms)"
set boxwidth 0.05
set style data histogram
set style histogram cluster
set style boxplot nooutliers
set xtics ("lvl 0" 0.000000,"lvl 1" 0.100000,"lvl 2" 0.200000,"lvl 3" 0.300000,"lvl 4" 0.400000,"lvl 5" 0.500000,"lvl 6" 0.600000,"lvl 7" 0.700000,"lvl 8" 0.800000)
set xrange [-0.1:0.900000]
set yrange [0:]
set title "Geometry complexity levels - Scene Forest" font ", 16"
plot \
"../../Data/Forest_0#0.data" using (0.000000):1:xticlabels(1) w boxplot t "Forest lvl 0",\
"../../Data/Forest_1#0.data" using (0.100000):1:xticlabels(1) w boxplot t "Forest lvl 1",\
"../../Data/Forest_2#0.data" using (0.200000):1:xticlabels(1) w boxplot t "Forest lvl 2",\
"../../Data/Forest_3#0.data" using (0.300000):1:xticlabels(1) w boxplot t "Forest lvl 3",\
"../../Data/Forest_4#0.data" using (0.400000):1:xticlabels(1) w boxplot t "Forest lvl 4",\
"../../Data/Forest_5#0.data" using (0.500000):1:xticlabels(1) w boxplot t "Forest lvl 5",\
"../../Data/Forest_6#0.data" using (0.600000):1:xticlabels(1) w boxplot t "Forest lvl 6",\
"../../Data/Forest_7#0.data" using (0.700000):1:xticlabels(1) w boxplot t "Forest lvl 7",\
"../../Data/Forest_8#0.data" using (0.800000):1:xticlabels(1) w boxplot t "Forest lvl 8",\
